version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysqlCuentas
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cuentas
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3308:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/Cuentas.sql
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-network

  cuentas-app:
    image: cuentas-app
    container_name: cuentas-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlCuentas:3306/cuentas
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge

volumes:
  mysql-data:
